export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST'
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS'
export const MOVIE_DETAIL_FAIL = 'MOVIE_DETAIL_FAIL'

export const MOVIE_CREATE_REVIEW_REQUEST = 'MOVIE_CREATE_REVIEW_REQUEST'
export const MOVIE_CREATE_REVIEW_SUCCESS = 'MOVIE_CREATE_REVIEW_SUCCESS'
export const MOVIE_CREATE_REVIEW_FAIL = 'MOVIE_CREATE_REVIEW_FAIL'
export const MOVIE_CREATE_REVIEW_RESET = 'MOVIE_CREATE_REVIEW_RESET'

export const MOVIE_GET_REVIEW_REQUEST = 'MOVIE_GET_REVIEW_REQUEST'
export const MOVIE_GET_REVIEW_SUCCESS = 'MOVIE_GET_REVIEW_SUCCESS'
export const MOVIE_GET_REVIEW_FAIL = 'MOVIE_GET_REVIEW_FAIL'
