export const SHOW_LIST_REQUEST = 'SHOW_LIST_REQUEST'
export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS'
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL'

export const SHOWBYLANG_LIST_REQUEST = 'SHOWBYLANG_LIST_REQUEST'
export const SHOWBYLANG_LIST_SUCCESS = 'SHOWBYLANG_LIST_SUCCESS'
export const SHOWBYLANG_LIST_FAIL = 'SHOWBYLANG_LIST_FAIL'

export const SHOW_DETAIL_REQUEST = 'SHOW_DETAIL_REQUEST'
export const SHOW_DETAIL_SUCCESS = 'SHOW_DETAIL_SUCCESS'
export const SHOW_DETAIL_FAIL = 'SHOW_DETAIL_FAIL'